[package]
name = "typey_birb"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/rparrett/typey_birb"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.11", features = ["jpeg"] }
bevy-inspector-egui = { version = "0.19", optional = true }
bevy_asset_loader = "0.17"
bevy_pipelines_ready = "0.1.1"

rand = "0.8"
