[package]
name = "typey_birb"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/rparrett/typey_birb"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.14", features = ["jpeg"] }
bevy-inspector-egui = { version = "0.25", optional = true }
bevy_asset_loader = "0.21"
bevy_pipelines_ready = "0.4"

rand = "0.8"

# Disable low-severity logs at compile time for performance.
log = { version = "0.4", features = [
    "max_level_debug",
    "release_max_level_warn",
] }

[lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[profile.dist]
inherits = "release"
lto = "thin"

[profile.web-dist]
inherits = "dist"
opt-level = "s"
