[package]
name = "typey_birb"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/rparrett/typey_birb"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.14.0-rc.2", features = ["jpeg"] }
bevy-inspector-egui = { version = "0.23", optional = true }
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader", branch = "bevy_main" }
bevy_pipelines_ready = { git = "https://github.com/rparrett/bevy_pipelines_ready", branch = "bevy-0.14" }

rand = "0.8"

[lints.clippy]
type_complexity = "allow"
